function setRefreshProgress(running,message,current=0,totalCount=0,kind='ok'){
 const box=document.getElementById('refreshProgress'),text=document.getElementById('refreshProgressText'),fill=document.getElementById('refreshProgressFill'),button=document.getElementById('refreshBtn');if(!box||!text||!fill||!button)return;
 box.hidden=false;text.textContent=message;const percent=totalCount>0?Math.min(100,Math.max(0,current/totalCount*100)):(running?8:100);fill.style.width=`${percent}%`;fill.style.background=kind==='error'?'var(--bad)':kind==='warn'?'var(--warn)':'var(--good)';button.disabled=running;button.textContent=running?`↻ Actualizando${totalCount?` ${current}/${totalCount}`:'…'}`:'↻ Actualizar cartera';button.setAttribute('aria-busy',running?'true':'false');
}
function allPortfolioMarketPositions(){
 if(!cloudSnapshot)return state.positions||[];const activePortfolioIds=new Set((state.portfolios||[]).filter(p=>p.active!==false).map(p=>p.id)),accounts=(cloudSnapshot.accounts||[]).filter(a=>a.active!==false&&activePortfolioIds.has(a.portfolio_id)),accountIds=new Set(accounts.map(a=>a.id)),ops=(cloudSnapshot.ops||[]).filter(o=>accountIds.has(o.account_id)),rules=(cloudSnapshot.recurringRules||[]).filter(r=>accountIds.has(r.account_id)&&activePortfolioIds.has(r.portfolio_id)),recurring=expandRecurringRules(rules,cloudSnapshot.navs||[],cloudSnapshot.listingPrices||[]),positions=buildPositions([...ops,...recurring.operations],accounts,cloudSnapshot.funds||[],cloudSnapshot.navs||[],cloudSnapshot.listingPrices||[]),accountMap=Object.fromEntries(accounts.map(a=>[a.id,a])),portfolioMap=Object.fromEntries((state.portfolios||[]).map(p=>[p.id,p.name]));return positions.map(p=>{const account=accountMap[p.accountId];return{...p,portfolioName:portfolioMap[account?.portfolio_id]||'Cartera'}});
}
function refreshTargetKey(x){return `${x.isin}|${x.listingSymbol||''}`}
function refreshTargets(){
 const map=new Map();for(const p of allPortfolioMarketPositions()){const key=refreshTargetKey(p),current=map.get(key);if(current){if(p.portfolioName&&!current.portfolios.includes(p.portfolioName))current.portfolios.push(p.portfolioName);continue}map.set(key,{key,isin:p.isin,listingSymbol:p.listingSymbol||null,name:meta(p).name||p.isin,navDate:p.navDate||null,portfolios:p.portfolioName?[p.portfolioName]:[]})}return[...map.values()].sort((a,b)=>String(a.navDate||'').localeCompare(String(b.navDate||''))||a.name.localeCompare(b.name,'es'));
}
function refreshErrorText(err){
 const code=String(err?.code||err?.payload?.error||err?.message||'ERROR_DESCONOCIDO').toUpperCase(),known={INSTRUMENT_NOT_FOUND:'El ISIN no aparece en ninguna fuente disponible.',EODHD_SEARCH_FAILED:'EODHD no respondió al buscar el ISIN.',EODHD_SEARCH_UNAVAILABLE:'No se pudo conectar con EODHD.',EODHD_HISTORY_FAILED:'EODHD no devolvió el histórico solicitado.',TRADEGATE_QUOTE_UNAVAILABLE:'Tradegate no devolvió una cotización válida.',LISTING_NOT_FOUND:'La bolsa seleccionada ya no está disponible.',SERVER_CONFIGURATION_INCOMPLETE:'Falta configurar alguna credencial del servicio de actualización.',INVALID_SESSION:'La sesión de Supabase ha caducado.'};return known[code]||String(err?.message||'Error de actualización');
}
async function refreshOneTarget(target){
 const startedAt=new Date().toISOString();try{const result=await resolveFund(target.isin,true,false,target.listingSymbol||null,true),quote=result?.latest_nav||null,stale=result?.quote_status?.stale===true||!quote?.date,status=!quote?.date?'failed':stale?'stale':'updated';return{...target,status,source:quote?.source||result?.sources?.identity_nav||null,quoteDate:quote?.date||null,quoteValue:Number.isFinite(+quote?.nav)?+quote.nav:null,currency:quote?.currency||null,historyReason:result?.history?.reason||null,historyRows:+result?.history?.rows_inserted||0,diagnostics:result?.diagnostics||[],error:status==='failed'?'No se obtuvo un VL/precio válido.':null,startedAt,finishedAt:new Date().toISOString()}}catch(err){return{...target,status:'failed',source:null,quoteDate:null,quoteValue:null,currency:null,historyReason:null,historyRows:0,diagnostics:err?.payload?.diagnostics||[],error:refreshErrorText(err),errorCode:err?.code||err?.payload?.error||null,startedAt,finishedAt:new Date().toISOString()}}
}
async function runRefreshTargets(targets){
 const rows=new Array(targets.length);let cursor=0,completed=0;const workers=Math.min(3,Math.max(1,targets.length));async function worker(){while(true){const index=cursor++;if(index>=targets.length)return;const target=targets[index];setRefreshProgress(true,`Actualizando ${completed+1} de ${targets.length}: ${target.name}`,completed,targets.length);rows[index]=await refreshOneTarget(target);completed++;const errors=rows.filter(Boolean).filter(x=>x.status==='failed').length;setCloudStatus(`Actualizando todos los perfiles… ${completed}/${targets.length}`);setRefreshProgress(true,`Procesados ${completed} de ${targets.length}`,completed,targets.length,errors?'warn':'ok')}}await Promise.all(Array.from({length:workers},()=>worker()));return rows;
}
function refreshReportSummary(rows){return{updated:rows.filter(x=>x.status==='updated').length,stale:rows.filter(x=>x.status==='stale').length,failed:rows.filter(x=>x.status==='failed').length}}
async function refreshAllMarketData(showNotice=true){
 setRefreshProgress(true,'Cargando los fondos de todos los perfiles…',0,0);await syncFromCloud(false);const targets=refreshTargets();setCloudStatus(`Actualizando todos los perfiles… 0/${targets.length}`);setRefreshProgress(true,targets.length?'Preparando todos los perfiles…':'No hay posiciones que actualizar',0,targets.length);if(!targets.length){setRefreshProgress(false,'No hay posiciones que actualizar.',0,0);return{updated:0,stale:0,failed:0,rows:[]}}
 const rows=await runRefreshTargets(targets);await syncFromCloud(false);const summary=refreshReportSummary(rows);state.refreshReport={startedAt:rows[0]?.startedAt||new Date().toISOString(),finishedAt:new Date().toISOString(),...summary,rows};saveCache();localStorage.setItem(AUTO_REFRESH_KEY,new Date().toISOString());const parts=[`${summary.updated} actualizados`];if(summary.stale)parts.push(`${summary.stale} atrasados`);if(summary.failed)parts.push(`${summary.failed} con error`);const resultText=`Todos los perfiles procesados: ${parts.join(', ')}.`;setRefreshProgress(false,resultText,targets.length,targets.length,summary.failed?'error':summary.stale?'warn':'ok');setCloudStatus(`Sincronizado con Supabase · ${resultText}`,summary.failed?'error':summary.stale?'warn':'');renderAnalysis();if(showNotice)alert(resultText);return{...summary,rows}
}
async function retryRefreshKeys(keys){
 const wanted=new Set(keys),old=state.refreshReport?.rows||[],targets=old.filter(x=>wanted.has(x.key)).map(x=>({key:x.key,isin:x.isin,listingSymbol:x.listingSymbol||null,name:x.name||x.isin,navDate:x.quoteDate||null,portfolios:x.portfolios||[]}));if(!targets.length)return;setRefreshProgress(true,'Reintentando instrumentos fallidos…',0,targets.length);const retried=await runRefreshTargets(targets);await syncFromCloud(false);const byKey=new Map(retried.map(x=>[x.key,x])),rows=old.map(x=>byKey.get(x.key)||x),summary=refreshReportSummary(rows);state.refreshReport={startedAt:state.refreshReport?.startedAt||new Date().toISOString(),finishedAt:new Date().toISOString(),...summary,rows};saveCache();const text=`Reintento completado: ${retried.filter(x=>x.status==='updated').length} actualizados, ${retried.filter(x=>x.status==='stale').length} atrasados y ${retried.filter(x=>x.status==='failed').length} con error.`;setRefreshProgress(false,text,targets.length,targets.length,retried.some(x=>x.status==='failed')?'error':retried.some(x=>x.status==='stale')?'warn':'ok');renderAll();alert(text)
}
window.retryRefreshTarget=key=>retryRefreshKeys([key]);window.retryFailedRefreshes=()=>retryRefreshKeys((state.refreshReport?.rows||[]).filter(x=>x.status==='failed').map(x=>x.key));
async function refreshPortfolio(){const button=document.getElementById('refreshBtn');if(button?.disabled)return;state.lastValue=total();saveCache();try{await refreshAllMarketData(true)}catch(err){console.error(err);setRefreshProgress(false,'No se pudo completar la actualización.',0,1,'error');alert('No se pudo actualizar la cartera: '+err.message)}}
function startupRefreshDue(){const raw=localStorage.getItem(AUTO_REFRESH_KEY);if(!raw)return true;const t=Date.parse(raw);if(!Number.isFinite(t))return true;return Date.now()-t>=12*3600*1000}
async function refreshOnStartup(){if(!state.positions.length||!startupRefreshDue())return;state.lastValue=total();saveCache();const el=document.getElementById('sinceUpdate');if(el)el.innerHTML='<span class="muted">Actualizando…</span>';setCloudStatus('Actualizando mercados…');try{await refreshAllMarketData(false)}catch(err){console.warn('Auto refresh',err);setRefreshProgress(false,'La actualización automática quedó pendiente.',0,1,'warn');setCloudStatus('Sincronizado con Supabase · actualización pendiente','warn')}}
function exportBackup(){const payload={app:'Mi Cartera',appVersion:APP_VERSION,schemaVersion:DATA_SCHEMA_VERSION,exportedAt:new Date().toISOString(),cloudProject:SUPABASE_URL,state,cloudData:cloudSnapshot};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`mi-cartera-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
