begin;

-- MI CARTERA v0.4.0
-- Histórico proxy para ETFs/listados sin serie exacta suficiente.
-- La serie proxy se marca siempre como aproximada y nunca se usa para validar
-- operaciones con el umbral del 0,1 %.

insert into public.app_meta (key, value)
values ('app_version', '0.4.0')
on conflict (key)
do update set value = excluded.value, updated_at = now();

insert into public.app_meta (key, value)
values ('schema_version', '6')
on conflict (key)
do update set value = excluded.value, updated_at = now();

alter table public.listing_prices
  add column if not exists is_approximate boolean not null default false,
  add column if not exists proxy_symbol text,
  add column if not exists calibration_factor numeric,
  add column if not exists approximation_method text,
  add column if not exists calibration_date date;

create index if not exists listing_prices_exact_idx
  on public.listing_prices (provider_symbol, price_date desc, is_approximate);

create table if not exists public.listing_history_proxies (
  target_symbol text primary key references public.instrument_listings(provider_symbol) on delete cascade,
  proxy_symbol text not null references public.instrument_listings(provider_symbol) on delete cascade,
  method text not null,
  calibration_date date not null,
  calibration_factor numeric not null,
  target_currency text,
  proxy_currency text,
  fx_symbol text,
  fx_inverted boolean not null default false,
  source text not null default 'EODHD proxy history',
  updated_at timestamptz not null default now()
);

create index if not exists listing_history_proxies_proxy_idx
  on public.listing_history_proxies (proxy_symbol);

alter table public.listing_history_proxies enable row level security;

drop policy if exists "authenticated_read_listing_history_proxies" on public.listing_history_proxies;
create policy "authenticated_read_listing_history_proxies"
on public.listing_history_proxies for select
to authenticated
using (true);

grant select on public.listing_history_proxies to authenticated;
grant all on public.listing_history_proxies to service_role;

-- Las filas existentes son datos exactos de sus respectivas fuentes.
update public.listing_prices
set is_approximate = false
where is_approximate is distinct from false;


create table if not exists public.market_refresh_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null default 'running',
  instruments integer not null default 0,
  successes integer not null default 0,
  failures integer not null default 0,
  details jsonb
);

alter table public.market_refresh_runs enable row level security;

drop policy if exists "authenticated_read_market_refresh_runs" on public.market_refresh_runs;
create policy "authenticated_read_market_refresh_runs"
on public.market_refresh_runs for select
to authenticated
using (true);

grant select on public.market_refresh_runs to authenticated;
grant all on public.market_refresh_runs to service_role;

commit;
